### ISSUE TITLE
Package not installing dependencies

### ISSUE THREAD

**Issue by colmjude** [digital-land/digital-land-frontend#1]
When I `npm install digital-land-frontend` the package dependencies are not installed. These are needed for the build scripts to run.

To get it working I had to npm install the dependencies directly.

This is an annoying extra step to have to go through if you want to use digital-land-frontend in other projects.

Hopefully we can sort this so that all dependencies are automatically installed at the same time as installing digital-land-frontend

**Comment by paulmsmith** [comment]
Still not had time to look at this but found using [install-local npm package](https://www.npmjs.com/package/install-local) works around this for now.
